version: "3"

services:
  postgres:
    image: postgres:11.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: dockerExample
  app:
    build: .
    command: yarn run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    depends_on:
      - postgres